require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
-- require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.neogen"
require "user.orgmode"
-- require "user.bazel"
require "user.dap"
require "user.aerial"
require "user.pomo"
require "user.noice"
require "user.goto-preview"
require "user.transparent"
-- require "user.gen"
